framework:
    messenger:
        transports:
            async_export:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0
                options:
                    exchange:
                       name: unread_messages
                    queues:
                       unread_messages: ~
        routing:
            # Route your messages to the transports
            # 'App\Service\Message\ExportMessage': async_export
