oneup_uploader:
    chunks:
        maxage: 86400
        storage:
            directory: '%kernel.cache_dir%/uploader/chunks'

    mappings:

        gallery:
            frontend: fineuploader
            max_size: 100000000 # 100 MB
            enable_progress: true       
            enable_cancelation: true   
            namer: app_upload_namer
            storage:
                type: flysystem
                filesystem: oneup_flysystem.document_filesystem