security:

    session_fixation_strategy: invalidate

    encoders:
        App\Entity\User: bcrypt

    providers:
        database_users:
            entity: { class: App\Entity\User, property: username }

    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_MODERATOR: [ROLE_USER, ROLE_MODERATOR]
        ROLE_SUPERADMIN: [ROLE_MODERATOR, ROLE_SUPERADMIN]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            pattern: ^/
            form_login:
                check_path: security_login
                login_path: security_login
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /

            logout:
                path: security_logout
                target: security_login

            security: true

    access_control:
        - { path: ^/$, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_SUPERADMIN }
        - { path: ^/_uploader, roles: ROLE_USER }
        - { path: ^(login|register)$, roles: IS_AUTHENTICATED_ANONYMOUSLY }