#index:
#    path: /
#    controller: App\Controller\DefaultController::index

craue_config_settings_modify:
  path: /admin/settings
  defaults:
    _controller: Craue\ConfigBundle\Controller\SettingsController::modifyAction